name: Compile virion

# Controls when the action will run. 
on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # run once a week
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  GenBank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3'
    - name: dependencies!!!!
      run: |
        sudo apt-get install libcurl4-openssl-dev
        sudo Rscript -e 'install.packages(c("taxize","rgbif","doParallel","tidyverse","magrittr","plyr","zip", "fs", "PresenceAbsence"))'
    - name: Download GenBank
      run: |
        Rscript -e 'source("Code/02_1a_Download GenBank.R")'
    - name: Digest GenBank
      run: |
        Rscript -e 'source("Code/02_1b_Digest GenBank.R")'
    - name: Format GenBank
      run: |
        Rscript -e 'source("Code/02_1c_Format GenBank.R")'
    - name: Save artifacts
      uses: actions/upload-artifacts@v2
      with:
        name: GenBankFormatted
        path: Intermediate/Formatted/GenbankFormatted.csv.gz
  Finish:
    runs-on: ubuntu-latest
    needs: [GenBank]
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.3'
      - name: dependencies!!!!
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo Rscript -e 'install.packages(c("taxize","rgbif","doParallel","tidyverse","magrittr","plyr","zip", "fs", "PresenceAbsence"))'
      - name: Get GenBank
        uses: actions/download-artifacts@v2
        with:
          name: GenBankFormatted
      - name: Merge clean files
        run: |
          Rscript -e 'source("Code/03_Merge clean files.R")'
      - name: High level checks
        run: |
          Rscript -e 'source("Code/04_High level VIRION checks.R")'
      - name: Dissolve VIRION
        run: |
          Rscript -e 'source("Code/05_Dissolve VIRION.R")'
      - name: Save the artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: VIRION
          path: Virion
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: Virion # The folder the action should deploy.
