name: Compile virion

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  # run once a week
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  doTheThing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies!!!!
      run: |
        sudo Rscript -e 'install.packages(c("taxize","rgbif","doParallel","tidyverse","magrittr","plyr","zip", "fs", "PresenceAbsence"))'
    - name: run 01-Clean-GenBank-edgelist (implicitly runs 00)
      run: |
        Rscript -e 'source("Code/01_Clean_GenBank.R")'
    - name: create VIRION
      run: |
        Rscript -e 'source("Code/02_Merge_in_Clover.R")'
    - name: run 03 format SRA and merge into VIRION
      run: |
        Rscript -e 'source("Code/03_Clean_SRA_Merge.R")'
